# Generated by Django 2.0.6 on 2018-08-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_manager', '0044_auto_20180726_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Reporte de venta de documentos',
                'verbose_name_plural': 'Reporte de venta de documentos',
                'proxy': True,
                'indexes': [],
            },
            bases=('document_manager.document',),
        ),
    ]
