#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


if [[ "${DOCKER_DEV_ENV}" == "vscode" ]]; then
	sleep infinity
else
	python manage.py migrate
    python manage.py runserver_plus 0.0.0.0:8000
fi