# Generated by Django 2.0.6 on 2018-06-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('police_type', models.CharField(choices=[('TCP', 'Términos y condiciones'), ('PP', 'Política de privacidad y tratamiento de datos'), ('CMP', 'Política de tratamiento de Cookies')], max_length=2, unique=True, verbose_name='Tipo de Política')),
            ],
            options={
                'verbose_name': 'Politica',
            },
        ),
    ]
