# Generated by Django 2.0.6 on 2018-06-12 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='last_update_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 12, 20, 12, 27, 789004, tzinfo=utc), verbose_name='Fecha de última actualización'),
            preserve_default=False,
        ),
    ]
