# Generated by Django 2.0.6 on 2018-06-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0002_policy_last_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='police_type',
            field=models.CharField(choices=[('TCP', 'Términos y condiciones'), ('PP', 'Política de privacidad y tratamiento de datos'), ('CMP', 'Política de tratamiento de Cookies')], max_length=3, unique=True, verbose_name='Tipo de Política'),
        ),
    ]
