# Generated by Django 2.0.6 on 2018-06-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0005_faqcategory_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_page_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Título (Quienes sómos)')),
                ('about_page_content', models.TextField(blank=True, null=True, verbose_name='Contenido (Quienes sómos)')),
                ('about_page_image', models.ImageField(blank=True, null=True, upload_to='site/aboutus/')),
            ],
            options={
                'verbose_name': 'Configuración de sitio',
            },
        ),
    ]
