# Generated by Django 2.0.6 on 2018-07-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0007_auto_20180612_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides', verbose_name='Imagen')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto')),
                ('youtube_video_link', models.URLField(blank=True, null=True, verbose_name='Link de Youtube')),
            ],
            options={
                'verbose_name': 'Slide del home',
                'verbose_name_plural': 'Slides del home',
            },
        ),
    ]
