# Generated by Django 2.0.6 on 2018-07-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0009_auto_20180704_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
    ]
