# Generated by Django 2.0.6 on 2018-07-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0010_slideritem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='landing_contract_info',
            field=models.TextField(blank=True, null=True, verbose_name='¿Por qué construir un contrato responsablemente? (landing)'),
        ),
    ]
