# Generated by Django 2.0.6 on 2018-07-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0011_siteconfig_landing_contract_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_page_image',
            field=models.ImageField(blank=True, null=True, upload_to='about-us', verbose_name='Imagen (Quienes somos)'),
        ),
    ]
