# Generated by Django 2.0.6 on 2018-08-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0012_siteconfig_about_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='about_page_content',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Contenido (Quienes sómos)'),
        ),
    ]
