# Generated by Django 2.0.6 on 2018-08-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0015_auto_20180802_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='meta_tags',
            field=models.TextField(blank=True, null=True, verbose_name='Tags de SEO y SEM'),
        ),
    ]
