# Generated by Django 2.0.6 on 2018-09-06 14:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0016_siteconfig_meta_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
