# Generated by Django 2.0.9 on 2018-11-21 03:12

from django.db import migrations
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0018_auto_20180924_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
