# Generated by Django 2.0.9 on 2018-12-21 00:04

from django.db import migrations
import tratum.ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0019_auto_20181121_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=tratum.ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
