# Generated by Django 2.0.9 on 2019-01-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0020_auto_20181221_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Glosario',
            },
        ),
        migrations.CreateModel(
            name='GlossaryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True, verbose_name='Palabra')),
                ('meaning', models.TextField(verbose_name='Significado')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_info.GlossaryCategory')),
            ],
            options={
                'verbose_name': 'Item de glosario',
                'verbose_name_plural': 'Items de glosario',
            },
        ),
    ]
