# Generated by Django 2.0.9 on 2019-01-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0022_auto_20190119_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryitem',
            options={'ordering': ['word'], 'verbose_name': 'Item de glosario', 'verbose_name_plural': 'Items de glosario'},
        ),
    ]
