# Generated by Django 2.0.9 on 2019-03-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0023_auto_20190119_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='data_policy_file',
            field=models.FileField(blank=True, null=True, upload_to='legal', verbose_name='Documento de política de tratamiento de datos'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='terms_file',
            field=models.FileField(blank=True, null=True, upload_to='legal', verbose_name='Documento de términos y condiciones'),
        ),
    ]
