# Generated by Django 2.0.9 on 2019-03-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0024_auto_20190326_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Youtube (landing)'),
        ),
    ]
