# Generated by Django 2.0.9 on 2019-04-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0025_siteconfig_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título de categoría')),
                ('image', models.ImageField(help_text='La resolución es 1920 x 1080p', upload_to='main_categories', verbose_name='Imagen')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('button_title', models.CharField(max_length=100, verbose_name='Título de botón (para home)')),
                ('button_url', models.URLField(verbose_name='URL para botón de categoría')),
            ],
        ),
    ]
