# Generated by Django 2.0.9 on 2019-04-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0026_maincategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Categoría principal', 'verbose_name_plural': 'Categorías principales'},
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
