# Generated by Django 2.0.9 on 2019-05-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_info', '0027_auto_20190405_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='landing_bundles_info',
            field=models.TextField(blank=True, null=True, verbose_name='Paquetes(landing)'),
        ),
    ]
