# Generated by Django 2.0.6 on 2018-06-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0007_auto_20180606_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Documento'},
        ),
        migrations.AlterField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='¿Disponible en la plataforma?'),
        ),
    ]
