# Generated by Django 2.0.6 on 2018-06-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0008_auto_20180606_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='visible',
        ),
    ]
