# Generated by Django 2.0.6 on 2018-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0009_remove_category_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
