# Generated by Django 2.0.6 on 2018-06-12 23:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0011_documentfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_manager.Document')),
            ],
        ),
    ]
