# Generated by Django 2.0.6 on 2018-06-13 00:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0012_documentsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfield',
            name='id',
        ),
        migrations.AddField(
            model_name='documentfield',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
