# Generated by Django 2.0.6 on 2018-06-13 00:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0014_auto_20180612_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('youtube_help_video_link', models.URLField(blank=True, null=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_manager.Document')),
            ],
        ),
    ]
