# Generated by Django 2.0.6 on 2018-06-13 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0015_documentfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsection',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
