# Generated by Django 2.0.6 on 2018-06-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0016_documentsection_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='key',
        ),
        migrations.RemoveField(
            model_name='documentsection',
            name='key',
        ),
    ]
