# Generated by Django 2.0.6 on 2018-06-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0017_auto_20180615_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsection',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
