# Generated by Django 2.0.6 on 2018-06-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0019_auto_20180619_1454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentsection',
            unique_together={('name', 'document')},
        ),
    ]
