# Generated by Django 2.0.6 on 2018-06-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0020_auto_20180619_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_manager.DocumentSection'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_manager.Document'),
        ),
    ]
