# Generated by Django 2.0.6 on 2018-06-19 21:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0021_auto_20180619_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsection',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterUniqueTogether(
            name='documentfield',
            unique_together={('name', 'document')},
        ),
    ]
