# Generated by Django 2.0.6 on 2018-06-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0024_document_formated'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='field_type',
            field=models.CharField(blank=True, choices=[('NU', b'Num\xc3\xa9rico'), ('TX', 'Texto abierto'), ('DT', 'Fecha'), ('SE', b'Opciones de \xc3\xbanica respuesta'), ('LI', 'Listado'), ('GP', b'Agrupaci\xc3\xb3n de campos')], max_length=2, null=True, verbose_name='Tipo de campo'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_manager.Document', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de ayuda'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_manager.DocumentSection', verbose_name=b'Secci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='youtube_help_video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Youtube del video de ayuda'),
        ),
    ]
