# Generated by Django 2.0.6 on 2018-06-26 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0025_auto_20180626_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_manager.DocumentSection', verbose_name='Sección'),
        ),
    ]
