# Generated by Django 2.0.6 on 2018-06-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0029_documentfieldoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfield',
            options={'verbose_name': 'Campo'},
        ),
        migrations.AlterModelOptions(
            name='documentfieldoption',
            options={'verbose_name': 'Opción', 'verbose_name_plural': 'Opciones'},
        ),
        migrations.AlterModelOptions(
            name='documentsection',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
    ]
