# Generated by Django 2.0.6 on 2018-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0032_documentfield_field_group_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='formated',
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='document',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
