# Generated by Django 2.0.6 on 2018-07-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0033_auto_20180709_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='group_expression',
            field=models.TextField(blank=True, help_text='Indica la expresión final de cada campo del grupo mediante el lenguaje de formateo', null=True, verbose_name='Expresión regular de la agrupación'),
        ),
    ]
