# Generated by Django 2.0.6 on 2018-07-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0033_auto_20180709_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='decription',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
