# Generated by Django 2.0.6 on 2018-07-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0034_auto_20180717_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='decription',
            new_name='description',
        ),
    ]
