# Generated by Django 2.0.6 on 2018-07-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0035_auto_20180717_1611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('category', 'order')},
        ),
    ]
