# Generated by Django 2.0.6 on 2018-07-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0036_auto_20180717_1725'),
        ('document_manager', '0034_documentfield_group_expression'),
    ]

    operations = [
    ]
