# Generated by Django 2.0.6 on 2018-07-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0037_merge_20180718_1415'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
    ]
