# Generated by Django 2.0.6 on 2018-07-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0038_auto_20180718_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AddField(
            model_name='document',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción larga'),
        ),
        migrations.AddField(
            model_name='document',
            name='short_description',
            field=models.CharField(blank=True, help_text='Cantidad máxima de caracteres: 120', max_length=120, null=True, verbose_name='Descripción corta'),
        ),
    ]
