# Generated by Django 2.0.6 on 2018-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0041_auto_20180719_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='display_name',
            field=models.CharField(blank=True, help_text='Corresponde a la pregunta textual que verán los usuarios', max_length=255, null=True, verbose_name='Texto a mostrar'),
        ),
    ]
