# Generated by Django 2.0.6 on 2018-07-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0042_documentfield_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsection',
            name='display_name',
            field=models.CharField(blank=True, help_text='Corresponde a la pregunta textual que verán los usuarios', max_length=255, null=True, verbose_name='Texto a mostrar'),
        ),
    ]
