# Generated by Django 2.0.6 on 2018-08-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0044_auto_20180726_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='group_order',
            field=models.PositiveIntegerField(blank=True, help_text='Indica el orden de aparición del campo en el formulario (Sólo aplica para grupos)', null=True, verbose_name='Orden de campo en el grupo'),
        ),
    ]
