# Generated by Django 2.0.6 on 2018-08-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0045_documentfield_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='group_items',
            field=models.TextField(blank=True, help_text='Indica cada uno de los items de un campo múltiple, separados por *', null=True, verbose_name='Opciones del grupo'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='field_type',
            field=models.CharField(choices=[('NU', 'Numérico'), ('TX', 'Texto abierto'), ('DT', 'Fecha'), ('SE', 'Opciones de única respuesta'), ('SM', 'Opciones agrupadas'), ('LI', 'Listado'), ('GP', 'Agrupación de campos')], default='TX', max_length=2, verbose_name='Tipo de campo'),
        ),
    ]
