# Generated by Django 2.0.6 on 2018-08-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0046_auto_20180809_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfieldoption',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
    ]
