# Generated by Django 2.0.6 on 2018-08-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0050_auto_20180817_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='field_type',
            field=models.CharField(choices=[('NU', 'Numérico'), ('TX', 'Texto abierto'), ('DT', 'Fecha'), ('ND', 'Fecha natural'), ('SE', 'Opciones de única respuesta'), ('SM', 'Opciones agrupadas'), ('LI', 'Listado'), ('GP', 'Agrupación de campos')], default='TX', max_length=2, verbose_name='Tipo de campo'),
        ),
    ]
