# Generated by Django 2.0.6 on 2018-08-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0052_remove_documentfield_group_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsection',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de ayuda'),
        ),
    ]
