# Generated by Django 2.0.6 on 2018-08-27 20:01

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0053_documentsection_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='URL del video explicativo'),
        ),
    ]
