# Generated by Django 2.0.6 on 2018-08-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0054_auto_20180827_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='field_type',
            field=models.CharField(choices=[('NU', 'Numérico'), ('PR', 'Precio'), ('TX', 'Texto abierto'), ('DT', 'Fecha'), ('ND', 'Fecha natural'), ('SE', 'Opciones de única respuesta'), ('SM', 'Opciones agrupadas'), ('GP', 'Agrupación de campos')], default='TX', max_length=2, verbose_name='Tipo de campo'),
        ),
    ]
