# Generated by Django 2.0.6 on 2018-09-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0055_auto_20180830_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Indica el orden de aparición del campo en el formulario', null=True, verbose_name='Orden de campo en el formulario'),
        ),
        migrations.AddField(
            model_name='documentfieldoption',
            name='linked_fields',
            field=models.ManyToManyField(blank=True, related_name='linkedfields_set', to='document_manager.DocumentField', verbose_name='Campos de la opción (si aplica)'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='group_order',
            field=models.PositiveIntegerField(blank=True, help_text='Indica el orden de aparición del campo en el grupo corrspondiente (Sólo aplica para campos de una agrupación)', null=True, verbose_name='Orden de campo en el grupo'),
        ),
    ]
