# Generated by Django 2.0.6 on 2018-09-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0056_auto_20180903_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='field_type',
            field=models.CharField(choices=[('NU', 'Numérico'), ('PR', 'Precio'), ('TX', 'Texto abierto'), ('DT', 'Fecha'), ('ND', 'Fecha natural'), ('SE', 'Opciones de única respuesta'), ('DS', 'Opciones de única respuesta con preguntas dinámicas'), ('SM', 'Opciones de múltiple respuesta'), ('GP', 'Agrupación de campos')], default='TX', max_length=2, verbose_name='Tipo de campo'),
        ),
    ]
