# Generated by Django 2.0.6 on 2018-09-10 16:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0057_auto_20180906_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción larga'),
        ),
    ]
