# Generated by Django 2.0.6 on 2018-09-26 20:40

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0058_auto_20180910_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfieldoption',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_manager.Document', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='documentfieldoption',
            name='field',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='document', chained_model_field='document', on_delete=django.db.models.deletion.CASCADE, to='document_manager.DocumentField'),
        ),
    ]
