# Generated by Django 2.0.6 on 2018-09-26 20:46

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0059_auto_20180926_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfieldoption',
            name='field',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='document', chained_model_field='document', on_delete=django.db.models.deletion.CASCADE, to='document_manager.DocumentField', verbose_name='Campo al que pertenece la opción'),
        ),
    ]
