# Generated by Django 2.0.6 on 2018-10-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0060_auto_20180926_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Documento al que pertenece el campo', null=True, on_delete=django.db.models.deletion.CASCADE, to='document_manager.Document', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='field_group',
            field=models.ManyToManyField(blank=True, help_text='Para campos agrupados, indica que campos hacen parte del grupo', related_name='_documentfield_field_group_+', to='document_manager.DocumentField', verbose_name='Campos del grupo'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='name',
            field=models.CharField(help_text='Corresponde a la nombre interno del campo', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Si es el campo de una sección, indicar la sección', null=True, on_delete=django.db.models.deletion.CASCADE, to='document_manager.DocumentSection', verbose_name='Sección'),
        ),
    ]
