# Generated by Django 2.0.6 on 2018-10-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0061_auto_20181005_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='show_on_document',
            field=models.BooleanField(default=True, help_text='Si desactivas esta opción, la pregunta aparecerá en el formulario, pero no en el documento', verbose_name='¿Mostrar en el documento?'),
        ),
    ]
