# Generated by Django 2.0.6 on 2018-10-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0062_documentfield_show_on_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Si subes una archivo aquí, indicas que el documento no será un formulario, si no un archivo descargable. Ej: Liquidador de excel', null=True, upload_to='filedocuments', verbose_name='Documento de archivo'),
        ),
    ]
