# Generated by Django 2.0.6 on 2018-11-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0063_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Indica el orden de aparición del campo en el formulario', verbose_name='Orden de campo en el formulario'),
        ),
    ]
