# Generated by Django 2.0.9 on 2018-11-21 03:12

from django.db import migrations
import django.db.models.deletion
import tratum.smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0064_auto_20181113_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfield',
            options={'ordering': ['order', 'document'], 'verbose_name': 'Campo'},
        ),
        migrations.AlterField(
            model_name='documentfieldoption',
            name='field',
            field=tratum.smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='document', chained_model_field='document', on_delete=django.db.models.deletion.CASCADE, to='document_manager.DocumentField', verbose_name='Campo al que pertenece la opción'),
        ),
    ]
