# Generated by Django 2.0.9 on 2018-11-21 21:48

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0065_auto_20181121_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfieldoption',
            name='field',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='document', chained_model_field='document', on_delete=django.db.models.deletion.CASCADE, to='document_manager.DocumentField', verbose_name='Campo al que pertenece la opción'),
        ),
        migrations.AlterField(
            model_name='documentfieldoption',
            name='linked_fields',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='field', chained_model_field='document', horizontal=True, related_name='linkedfields_set', to='document_manager.DocumentField', verbose_name='Campos de la opción (si aplica)'),
        ),
    ]
