# Generated by Django 2.0.9 on 2018-11-21 22:03

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0066_auto_20181121_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='field_group',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='document', chained_model_field='document', help_text='Para campos agrupados, indica que campos hacen parte del grupo', related_name='_documentfield_field_group_+', to='document_manager.DocumentField', verbose_name='Campos del grupo'),
        ),
        migrations.AlterField(
            model_name='documentfieldoption',
            name='linked_fields',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='document', chained_model_field='document', horizontal=True, related_name='linkedfields_set', to='document_manager.DocumentField', verbose_name='Campos de la opción (si aplica)'),
        ),
    ]
