# Generated by Django 2.0.9 on 2018-12-21 00:04

from django.db import migrations, models
import smart_selects.db_fields
import tratum.ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0068_auto_20181121_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=tratum.ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Si subes una archivo aquí, indicas que el documento no será un formulario,\n                     si no un archivo descargable. Ej: Liquidador de excel', null=True, upload_to='filedocuments', verbose_name='Documento de archivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='long_description',
            field=tratum.ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción larga'),
        ),
        migrations.AlterField(
            model_name='documentfieldoption',
            name='linked_fields',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='document', chained_model_field='document', related_name='linkedfields_set', to='document_manager.DocumentField', verbose_name='Campos de la opción (si aplica)'),
        ),
        migrations.AlterField(
            model_name='documentsection',
            name='content',
            field=tratum.ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
