# Generated by Django 2.0.9 on 2019-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0069_auto_20181221_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfieldoption',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Indica el orden de aparición del campo en el formulario', verbose_name='Orden de campo en el formulario'),
        ),
    ]
