# Generated by Django 2.0.6 on 2018-06-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180612_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentbundle',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
    ]
