# Generated by Django 2.0.6 on 2018-07-24 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_manager', '0043_documentsection_display_name'),
        ('store', '0003_auto_20180612_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField(blank=True, null=True, verbose_name='Respuestas')),
                ('status', models.CharField(choices=[('CR', 'Creado'), ('PU', 'Comprado'), ('FI', 'Finalizado')], default='PU', max_length=2)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_manager.Document', verbose_name='Documento')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Documento de usuario',
                'verbose_name_plural': 'Documentos de usuarios',
            },
        ),
    ]
