# Generated by Django 2.0.6 on 2018-07-25 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
