# Generated by Django 2.0.6 on 2018-07-25 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userdocument_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
