# Generated by Django 2.0.6 on 2018-07-26 20:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20180725_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Respuestas'),
        ),
    ]
