# Generated by Django 2.0.6 on 2018-07-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20180725_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbundle',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Orden'),
        ),
    ]
