# Generated by Django 2.0.6 on 2018-08-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_invoice'),
        ('store', '0008_auto_20180726_1537'),
    ]

    operations = [
    ]
