# Generated by Django 2.0.6 on 2018-08-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20180803_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_manager.Document', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.DocumentBundle', verbose_name='Paquete'),
        ),
    ]
