# Generated by Django 2.0.6 on 2018-08-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20180806_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbundle',
            name='show_on_landing',
            field=models.BooleanField(default=False),
        ),
    ]
