# Generated by Django 2.0.6 on 2018-08-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_documentbundle_show_on_landing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='status',
            field=models.CharField(choices=[('CR', 'Creado'), ('PU', 'Comprado'), ('FI', 'Finalizado'), ('EX', 'Caducado')], default='PU', max_length=2),
        ),
    ]
