# Generated by Django 2.0.6 on 2018-08-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20180810_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='html_path',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
