# Generated by Django 2.0.6 on 2018-08-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_userdocument_html_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocument',
            name='html_path',
        ),
        migrations.AddField(
            model_name='userdocument',
            name='html_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=''),
        ),
    ]
