# Generated by Django 2.0.6 on 2018-08-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20180812_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='html_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='documents'),
        ),
    ]
