# Generated by Django 2.0.6 on 2018-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_userdocument_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='word_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='docxs'),
        ),
    ]
