# Generated by Django 2.0.6 on 2018-09-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_userdocument_word_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='pdf_file',
            field=models.FileField(blank=True, editable=False, max_length=500, null=True, upload_to='pdfs'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='word_file',
            field=models.FileField(blank=True, editable=False, max_length=500, null=True, upload_to='docxs'),
        ),
    ]
