# Generated by Django 2.0.6 on 2018-10-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20180924_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de pago'),
        ),
    ]
