# Generated by Django 2.0.9 on 2019-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20181223_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('AP', 'Aprobada'), ('PE', 'Pendiente'), ('CA', 'Cancelada'), ('RE', 'Rechazada'), ('ER', 'Error')], default='PE', max_length=50, verbose_name='Estado del Pago'),
        ),
    ]
