# Generated by Django 2.0.9 on 2020-06-29 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0024_auto_20190119_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('document_number', models.IntegerField(help_text='Para ilimitado dejarlo en 0', verbose_name='Número de documentos de la suscripción')),
                ('has_general_talks', models.BooleanField(default=True, verbose_name='Tiene charlas en temas de interés general?')),
                ('has_update_talks', models.BooleanField(default=False, verbose_name='Tiene charlas de actualidad normativa?')),
                ('virtual_consultant', models.IntegerField(default=0, verbose_name='Número de consultas jurídicas virtuales')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('show_on_landing', models.BooleanField(default=False, verbose_name='Ver en la landing?')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='UserDocumentsSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.UserDocument', verbose_name='Documento del usuario')),
            ],
            options={
                'verbose_name': 'Documento de la suscripción de usuario',
                'verbose_name_plural': 'Documentos de la suscripción de usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CR', 'Creado'), ('PU', 'Comprado'), ('FI', 'Finalizado'), ('EX', 'Caducado')], default='CR', max_length=2)),
                ('date_purchase', models.DateTimeField(verbose_name='Fecha de compra de suscripción')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Subscription', verbose_name='Suscripción')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción de usuario',
                'verbose_name_plural': 'Suscripciones de usuarios',
            },
        ),
        migrations.AddField(
            model_name='userdocumentssubscription',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.UserSubscription', verbose_name='Suscripción del usuario'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Subscription', verbose_name='Suscripción'),
        ),
    ]
