# Generated by Django 2.0.9 on 2020-06-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20200629_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumentssubscription',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de comprado'),
        ),
    ]
