# Generated by Django 2.0.6 on 2018-06-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0002_document_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
