# Generated by Django 2.0.6 on 2018-07-13 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Empresa')),
                ('employees_number', models.IntegerField(verbose_name='Número de empleados')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('sector', models.CharField(max_length=255, verbose_name='Sector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_companys', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compañía',
            },
        ),
        migrations.CreateModel(
            name='LogTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_log_terms', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Logs de Términos',
                'verbose_name': 'Log de términos',
            },
        ),
    ]
