# Generated by Django 2.0.6 on 2018-07-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='employees_number',
            field=models.IntegerField(blank=True, choices=[(1, 'Menos de 10'), (2, 'Entre 10 y 20'), (3, 'Entre 20 y 50'), (4, 'Más de 50')], null=True, verbose_name='Número de empleados'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_companys', to='users.Sector', verbose_name='Sector'),
        ),
    ]
