# Generated by Django 2.0.9 on 2019-03-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180725_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesión del usuario'),
        ),
    ]
